### ISSUE TITLE
First service status records automatically

### ISSUE THREAD

**Issue by bcoyte** [rporteous1/SurfPlus#46]
This has been implemented for Clubs, if DO's, UAV's, RWC's are wanted too, let me know.

_Originally posted by @rporteous1 in https://github.com/rporteous1/SurfPlus/issues/40#issuecomment-2172183022_
           

FYI this is only adds the first club paged.
Still a huge development in having a functional system, but would love to get subsequent entities added too.

**Comment by rporteous1** [comment]
> FYI this is only adds the first club paged.
> 
> Still a huge development in having a functional system, but would love to get subsequent entities added too. 

Are you sure? When I was testing yesterday it was adding each COT that I paged, may be worth someone manually checking each club in the code matches their COT as there may be some mix ups.

**Comment by rporteous1** [comment]
Will test further when I'm home.

**Comment by rporteous1** [comment]
Just tested, it is working for multiple clubs, for example, page "SurfPlus Testing" and "SOC DEMO Notification" and if you mark a person in both these groups as attending, both Test NSW Lifeguards (linked to SurfPlus Testing) and Test NSW Club (linked to SOC DEMO Notifications) are added as en route.

If you are able to test please @bcoyte and let me know if this is working like I described, if it isn't, let me know and I can look into a fix for it.

Good chance it's specific clubs only that are causing the issue.

**Comment by rporteous1** [comment]
Looking at the job I assume was an issue, looks like its as the club was marked as notified, will look into if there is a way to trigger clicking en route if it exists but isnt marked en route.

**Comment by rporteous1** [comment]
Fix has been implemented.

Unfortunately due to security limitations in Chrome Extensions, I'm unable to click the enroute button directly as SLSA have set it up in an odd way.

As a workaround, I've made an alert pop up telling the user to do it if the service is marked as notified and someone responds.
<img width="450" alt="image" src="https://github.com/rporteous1/SurfPlus/assets/160448581/acef1ca0-9523-4db9-bea5-5b1a0f29b74d">

I've also made the relevant "en route" cell flash orange if it meets the condition, so you know which unit needs to be marked as en route.
![Screen Recording 2024-06-19 at 10 58 06 PM](https://github.com/rporteous1/SurfPlus/assets/160448581/8518a545-5eb4-4da1-ad51-8239bec7d838)


If you're happy with this, let me know if I can close this issue.

**Comment by bcoyte** [comment]
Follow up on your next rostered shift please, not your personal time. 

The incident was a real one, not a simulation. Dual response page sent to two clubs. Lennox and Byron. One marked as notified, the other manually attached using [Add Service] which is the only way to add a time. 

For additional context there is an existing SLSA enhancement request to amend status times such as Notified/On Scene. 
STAT-254 
Status: To-do
Requested: 21/08/2024

**Comment by rporteous1** [comment]
Closing out due to above chrome extension manifest v3 limitations. 

May if time permits look into using SurfCom Map Search in the flow to trigger JS functions.

For now, follow this workflow - SurfCom Page > don’t attach unit > member responds with ETA > SurfPlus marks service en route
